name: Yarn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      uses: nuxt/actions-yarn@node-11
    - name: yarn lint
      uses: nuxt/actions-yarn@node-11
      with:
        args: lint
